apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: odpt-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: odpt
    spec:
      containers:
      - name: odpt
        image: asia.gcr.io/planet-pluto-dev/odpt:latest
        ports:
        - containerPort: 3010
