version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: odpt_dev
    hostname: odpt_dev
    ports:
      - "8306:3306"
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=zaqroot"
      - "MYSQL_DATABASE=odpt_dev"
      - "TZ=Asia/Tokyo"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d